<img src="http://hilpisch.com/tpq_logo.png" alt="The Python Quants" width="35%" align="right" border="0"><br>

# Python for Finance (2nd ed.)

**Mastering Data-Driven Finance**

&copy; Dr. Yves J. Hilpisch | The Python Quants GmbH

<img src="http://hilpisch.com/images/py4fi_2nd_shadow.png" width="300px" align="left">

# Numerical Computing with NumPy

## Arrays with Python Lists

In [1]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]  

In [2]:
m = [v, v, v]  
m  

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [3]:
m[1]

[0.5, 0.75, 1.0, 1.5, 2.0]

In [4]:
m[1][0]

0.5

In [5]:
v1 = [0.5, 1.5]
v2 = [1, 2]
m = [v1, v2]
c = [m, m]  
c

[[[0.5, 1.5], [1, 2]], [[0.5, 1.5], [1, 2]]]

In [6]:
c[1][1][0]

1

In [7]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]
m = [v, v, v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [8]:
v[0] = 'Python'
m

[['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0]]

In [9]:
from copy import deepcopy
v = [0.5, 0.75, 1.0, 1.5, 2.0]
m = 3 * [deepcopy(v), ]  
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [10]:
v[0] = 'Python'  
m  

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

## Regular NumPy Arrays

### The Basics

In [11]:
import numpy as np  

In [12]:
a = np.array([0, 0.5, 1.0, 1.5, 2.0])  
a

array([0. , 0.5, 1. , 1.5, 2. ])

In [13]:
type(a)  

numpy.ndarray

In [14]:
a = np.array(['a', 'b', 'c'])  
a

array(['a', 'b', 'c'], dtype='<U1')

In [15]:
a = np.arange(2, 20, 2)  
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
a = np.arange(8, dtype=float)  
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [17]:
a[5:]  

array([5., 6., 7.])

In [18]:
a[:2]  

array([0., 1.])

In [19]:
a.sum()  

28.0

In [20]:
a.std()  

2.29128784747792

In [21]:
a.cumsum()  

array([ 0.,  1.,  3.,  6., 10., 15., 21., 28.])

In [22]:
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [23]:
2 * a  

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [24]:
a ** 2  

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49.])

In [25]:
2 ** a  

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128.])

In [26]:
a ** a  

array([1.00000e+00, 1.00000e+00, 4.00000e+00, 2.70000e+01, 2.56000e+02,
       3.12500e+03, 4.66560e+04, 8.23543e+05])

In [27]:
np.exp(a)  

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03])

### Multiple Dimensions

In [28]:
b = np.array([a, a * 2])  
b

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 0.,  2.,  4.,  6.,  8., 10., 12., 14.]])

In [29]:
b[0]  

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [30]:
b[0, 2]  

2.0

In [31]:
b[:, 1]  

array([1., 2.])

In [32]:
b.sum()  

84.0

In [33]:
b.sum(axis=0)  

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21.])

In [34]:
b.sum(axis=1)  

array([28., 56.])

In [35]:
c = np.zeros((2, 3), dtype='i', order='C')  
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [36]:
c = np.ones((2, 3, 4), dtype='i', order='C')  
c

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [37]:
d = np.zeros_like(c, dtype=np.float16, order='C')  
d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float16)

In [38]:
d = np.ones_like(c, dtype=np.float16, order='C')  
d

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float16)

### Speed Comparison

In [39]:
import random
I = 5000

In [40]:
%time mat = [[random.gauss(0, 1) for j in range(I)] \
             for i in range(I)]  

CPU times: user 17.3 s, sys: 668 ms, total: 18 s
Wall time: 18.2 s


In [41]:
mat[0][:5]  

[-0.38440563073887263,
 0.42238142708053306,
 -0.3756872890109862,
 -0.952211294745453,
 0.9306841080644372]

In [42]:
%time sum([sum(l) for l in mat])  

CPU times: user 166 ms, sys: 988 µs, total: 167 ms
Wall time: 180 ms


-5707.027993798548

In [43]:
%time mat = np.random.standard_normal((I, I))  

CPU times: user 1.45 s, sys: 1.49 s, total: 2.94 s
Wall time: 2.97 s


In [44]:
%time mat.sum()  

CPU times: user 24.7 ms, sys: 2.96 ms, total: 27.7 ms
Wall time: 25.4 ms


-5256.890552937458

### Structured Arrays

In [45]:
dt = np.dtype([('Name', 'S10'), ('Age', 'i4'),
               ('Height', 'f'), ('Children/Pets', 'i4', 2)])  

In [46]:
dt  

dtype([('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [47]:
s = np.array([('Smith', 45, 1.83, (0, 1)),
              ('Jones', 53, 1.72, (2, 2))], dtype=dt)  

In [48]:
s  

array([(b'Smith', 45, 1.83, [0, 1]), (b'Jones', 53, 1.72, [2, 2])],
      dtype=[('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [49]:
type(s)  

numpy.ndarray

In [50]:
s['Name']  

array([b'Smith', b'Jones'], dtype='|S10')

In [51]:
s['Height'].mean()  

1.7750001

In [52]:
s[0]  

(b'Smith', 45, 1.83, [0, 1])

In [53]:
s[1]['Age']  

53

## Vectorization of Code

In [54]:
np.random.seed(100)
r = np.arange(12).reshape((4, 3))  
s = np.arange(12).reshape((4, 3)) * 0.5  

In [55]:
r  

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [56]:
s  

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

In [57]:
r + s  

array([[ 0. ,  1.5,  3. ],
       [ 4.5,  6. ,  7.5],
       [ 9. , 10.5, 12. ],
       [13.5, 15. , 16.5]])

In [58]:
2 * r + 3  

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

In [59]:
s = np.arange(0, 12, 4)  
s  

array([0, 4, 8])

In [60]:
r + s  

array([[ 0,  5, 10],
       [ 3,  8, 13],
       [ 6, 11, 16],
       [ 9, 14, 19]])

In [61]:
s = np.arange(0, 12, 3)  
s  

array([0, 3, 6, 9])

In [62]:
# causes intentional error
r + s  

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [63]:
r.transpose() + s  

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20]])

In [64]:
sr = s.reshape(-1, 1)  
sr

array([[0],
       [3],
       [6],
       [9]])

In [65]:
sr.shape  

(4, 1)

In [66]:
r + s.reshape(-1, 1)  

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20]])

In [67]:
def f(x):
    return 3 * x + 5  

In [68]:
f(0.5)  

6.5

In [69]:
f(r)  

array([[ 5,  8, 11],
       [14, 17, 20],
       [23, 26, 29],
       [32, 35, 38]])

<img src="http://hilpisch.com/tpq_logo.png" alt="The Python Quants" width="35%" align="right" border="0"><br>

<a href="http://tpq.io" target="_blank">http://tpq.io</a> | <a href="http://twitter.com/dyjh" target="_blank">@dyjh</a> | <a href="mailto:training@tpq.io">training@tpq.io</a>